### PR TITLE
Tutorial

### PR DESCRIPTION
**Pull request by amandadsmith**
Add walk-through tutorials to documentation

### CODE REVIEW

**Comment by crvernon** [comment]
@thurber once you make the first pass, I will review as well

**Review by thurber — APPROVED** [review]
i remove references to your personal directory in a few places, and reformatted some of the code blocks.

also remove the `docs/_build` folder from git tracking, as readthedocs is building automatically

**Review by crvernon — APPROVED** [review]
Looks good! I tested the and had a successful outcome.

**Comment by crvernon** [comment]
@thurber can you change the copyright to:

Copyright (c) 2021, Battelle Memorial Institute

**Comment by amandadsmith** [comment]
> @thurber can you change the copyright to:
> 
> Copyright (c) 2021, Battelle Memorial Institute

Will do this in master

**Pull request merged**
