### PR TITLE
Impute all the things

### PR DESCRIPTION
**Pull request by BenjaminStuermer**

### CODE REVIEW

**Comment by BenjaminStuermer** [comment]
Sorry for opening this so late - this branch has actually been done for a while, I was totally under the impression I had already opened a PR for it!

**Comment by amandadsmith** [comment]
Re:

`            # We will perform imputation on all the elements in the chunk *except* for the first and last
            # ones, which will be interpolated to smooth out the transition between computed and observed values
            indices_to_impute = indices[1:-1]`

Shouldn't it be `indices[1:-2]` if we want to exempt the first and last values?

And then the later statement:

`    df.interpolate(inplace=True)`

would automatically fill in the values at indices[0] and indices[-1] by averaging the two surrounding values?

**Comment by amandadsmith** [comment]
What triggers the parser to ask for a value? It runs automatically using the default values (which is great) but I'm curious how to change that value if we wanted to.

Can we also finish this sentence at the end here:

`parser.add_argument('--max-records-to-interpolate',
                    default=6,
                    type=int,
                    help="""The maximum number of consecutive records to interpolate. See the documentation of the
                            pandas.DataFrame.interpolate() method's "limit" argument for more details. Basically,
                            if fields are missing, those missing values will be set to a value interpolated linearly
                            using the values of the fields immediately preceding and following the missing field(s).
                            If a sequence of fields longer than this argument is encountered, only this maximum number
                            of values will be interpolated, and the remaining set of missing fields will be imputed
                            by averaging the ."""
                    )`

**Comment by BenjaminStuermer** [comment]
> Shouldn't it be `indices[1:-2]` if we want to exempt the first and last values?
I certainly thought so! I even tried to program it that way, but discovered that it made a slice that was one step smaller than I intended. You can try it out yourself in the Python command-line and see:

'''
>>> bob = list(range(1, 10))
>>> bob
[1, 2, 3, 4, 5, 6, 7, 8, 9]

>>> bob[1:-1]
[2, 3, 4, 5, 6, 7, 8]
'''

They made the positive and negative indexing symmetrical in slice definitions! But obviously you can't use -0 to refer to the final index; you just leave it blank:

```
>>> bob[1:]
[2, 3, 4, 5, 6, 7, 8, 9]
```

**Comment by BenjaminStuermer** [comment]
> What triggers the parser to ask for a value? It runs automatically using the default values (which is great) but I'm curious how to change that value if we wanted to.

It won't actually ask for a value, but you can pass one by adding the bits that are passed as the first argument to `parser.add_argument()`:

`python create_amy_epw_files.py --max-records-to-interpolate=42'

> 
> Can we also finish this sentence at the end here:
Oops! I've fixed that documentation.

**Review by amandadsmith — APPROVED** [review]

**Pull request merged**
